<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
  <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <UserSecretsId>14569fa6-6a18-4a80-9994-fa4638d26d2e</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.AI" Version="10.9.0" />
    <PackageReference Include="Microsoft.Extensions.AI.OpenAI" Version="10.9.0" />
    <PackageReference Include="ModelContextProtocol" Version="2.2.0" />
  </ItemGroup>

</Project>
